pull_request_rules:
    - name: automatic merge on CI success and review
      conditions:
          - status-success=kurlytail.gen-spring
      actions:
          merge:
              method: merge
              strict: true
          delete_head_branch: {}
